CREATE TABLE "GCG_6284_CLOCK_TYPE" (
 "EMPLOYEE" CHAR(5),
 "TS_MIN" NUMERIC(12,4),
 "IN_OUT" CHAR(3),
 "CLOCK_TYPE" CHAR(5) );
CREATE UNIQUE INDEX "GCG6284" USING 0 ON "GCG_6284_CLOCK_TYPE" ( "EMPLOYEE", "TS_MIN", "IN_OUT" );